CREATE DATABASE LIBRARY
GO

USE LIBRARY

CREATE TABLE [PERSONAS](--OBLIGATORIO
	[ID] INT NOT NULL IDENTITY(1,1),
	CONSTRAINT [PK_PERSONAS] PRIMARY KEY CLUSTERED ([ID]),
	[CEDULA] BIGINT NOT NULL UNIQUE,--OBLIGATORIO
	[NOMBRE] VARCHAR(80),
	[NUMERO] BIGINT,--OBLIGATORIO (NUMERO)
);

/*CREATE TABLE [AUTORES](
	[ID] INT NOT NULL IDENTITY(1,1),
	CONSTRAINT [PK_AUTORES] PRIMARY KEY CLUSTERED ([ID]),
	[SEUDONIMO] VARCHAR(40),
	--PAIS_ORIGEN VARCHAR(50),
);*/

CREATE TABLE [USUARIOS](--OBLIGATORIO
	[CODIGO_USUARIO] INT NOT NULL UNIQUE,--OBLIGATORIO
	CONSTRAINT [PK_USUARIOS] PRIMARY KEY CLUSTERED ([CODIGO_USUARIO]),
	[CORREO] VARCHAR(40),
	[CONTRASEÑA] VARBINARY(100),
	[PERSONA] INT,
	CONSTRAINT [FK_AUTORES_LIBROS] FOREIGN KEY ([PERSONA]) REFERENCES [PERSONAS] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION
);

/*CREATE TABLE [CATEGORIAS](
	[ID] INT NOT NULL IDENTITY (1, 1),
	[NOMBRE] VARCHAR(40),
	[DESCRIPCION] VARCHAR(50),
	CONSTRAINT [PK_CATEGORIAS] PRIMARY KEY CLUSTERED ([ID]),
);*/

CREATE TABLE [LIBROS](
	[ID] INT NOT NULL IDENTITY(1,1),
	CONSTRAINT [PK_LIBROS] PRIMARY KEY CLUSTERED ([ID]),
	[COD_LIBRO] INT NOT NULL UNIQUE,--OBLIGATORIO
	[NOMBRE_LIBRO] VARCHAR(30) NOT NULL,--OBLIGATORIO 
	[AÑO_PUBLICACION] DATE,
	[AUTOR] VARCHAR(40)
);

/*CREATE TABLE [LIBRO_AUTOR](
	[LIBRO] INT NOT NULL,
	[AUTOR] INT NOT NULL,
	CONSTRAINT [FK_AUTORES_LIBROS] FOREIGN KEY ([LIBRO]) REFERENCES [LIBROS] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT [FK_LIBROS_AUTORES] FOREIGN KEY ([AUTOR]) REFERENCES [AUTORES] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION
);*/

CREATE TABLE [COPIAS](
	[ID] INT NOT NULL IDENTITY (1, 1),
	CONSTRAINT [PK_COPIAS] PRIMARY KEY CLUSTERED ([ID]),
	[NOTAS] VARCHAR(55),	--[NOTAS_ESTADO] VARCHAR(55),--OBLIGATORIO
	[ESTADO] BIT DEFAULT 0,--OBLIGATORIO
	[LIBRO] INT,
	CONSTRAINT [FK_COPIAS_LIBROS] FOREIGN KEY ([LIBRO]) REFERENCES [LIBROS] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION
)

CREATE TABLE [PRESTAMOS](
	[ID] INT NOT NULL IDENTITY (1, 1),
	CONSTRAINT [PK_PRESTAMOS] PRIMARY KEY CLUSTERED ([ID]),
	[FECHA_INICIO] DATE,--OBLIGATORIO
	[USUARIO] INT,
	CONSTRAINT [FK_PRESTAMOS_USUARIOS] FOREIGN KEY ([USUARIO]) REFERENCES [USUARIOS] ([CODIGO_USUARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION
)

CREATE TABLE [DETALLES](
	[ID] INT NOT NULL IDENTITY (1, 1),
	CONSTRAINT [PK_DETALLES] PRIMARY KEY CLUSTERED ([ID]),
	[FECHA_FINAL] DATE,--OBLIGATORIO
	[PRESTAMO] INT NOT NULL,
	[COPIA] INT NOT NULL,
	CONSTRAINT [FK_DETALLES_PRESTAMOS] FOREIGN KEY ([PRESTAMO]) REFERENCES [PRESTAMOS] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT [FK_DETALLES_COPIAS] FOREIGN KEY ([COPIA]) REFERENCES [COPIAS] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION
)

INSERT INTO [PERSONAS]([CEDULA],[NOMBRE],[NUMERO])VALUES
(15123,'Esteban Quintero Yepes',3123448794),
(51232,'Juan Esteban Zapata Yepes',53243546),
(23433,'Esteban David Quintero Puerta',23435465),
(65413,'Esteban Emanuel Quintero Yepes',68563987),
(76454,'Angie Esteban Quintero',3123448794)
SELECT * FROM [PERSONAS]

/*INSERT INTO [AUTORES]([SEUDONIMO])VALUES
('Silleban'),
('Nevereban'),
('Noseban'),
('Guerrilleban'),
('Mariguneban')
SELECT * FROM [AUTORES]*/

/*INSERT INTO [AUTORES]([CODIGO_AUTOR],[SEUDONIMO],PAIS_ORIGEN)VALUES
(65427,'Silleban','Medellín'),
(9876,'Nevereban','Bogota'),
(098756,'Noseban','Bello'),
(98765,'Guerrilleban','Cali'),
(876502,'Mariguneban','Popayan')
SELECT * FROM [AUTORES]*/

INSERT INTO [USUARIOS]([CODIGO_USUARIO],[CORREO],[CONTRASEÑA],[PERSONA])VALUES
(235765,'Example@correo.com',ENCRYPTBYPASSPHRASE('PASSWORD','Holamundo'),2),
(543214,'Example@correo.com',ENCRYPTBYPASSPHRASE('PASSWORD','Holam'),1),
(6543269,'Example@correo.com',ENCRYPTBYPASSPHRASE('PASSWORD','Holapa'),3),
(9005566,'Example@correo.com',ENCRYPTBYPASSPHRASE('PASSWORD','Holasugra'),4),
(987653,'Example@correo.com',ENCRYPTBYPASSPHRASE('PASSWORD','Holainfiel'),5)
SELECT * FROM [USUARIOS]

/*INSERT INTO [CATEGORIAS] ([NOMBRE],[DESCRIPCION]) VALUES
('Terror','Mucho Terror'),
('Accion','Mucho Accion'),
('Comedia','Mucho Comedia'),
('Suspenso','Mucho Suspenso'),
('Drama','Mucho Drama')
SELECT * FROM [CATEGORIAS]*/

INSERT INTO [LIBROS]([COD_LIBRO],[NOMBRE_LIBRO],[AÑO_PUBLICACION],[AUTOR]) VALUES
(001,'Titulo1','1930-11-01','Silleban'),
(002,'Titulo2','1920-12-10','Nevereban'),
(003,'Titulo3','1910-09-21','Noseban'),
(004,'Titulo4','1940-07-23','Guerrilleban'),
(005,'Titulo5','1950-07-22','Mariguneban')
SELECT * FROM [LIBROS]

/*INSERT INTO [LIBRO_AUTOR]([LIBRO],[AUTOR])VALUES
(001,1),
(002,2),
(003,2),
(004,3),
(005,4),
(005,5)
SELECT * FROM [LIBRO_AUTOR]*/

INSERT INTO [COPIAS]([NOTAS],[ESTADO],[LIBRO])VALUES
('A',1,1),
('T',0,2),
('H',1,5),
('J',0,2),
('K',1,3),
('C',1,3)
SELECT * FROM [COPIAS]

INSERT INTO [PRESTAMOS]([FECHA_INICIO],[USUARIO])VALUES
('1980-01-25',235765),
('2001-12-12',543214),
('2002-11-15',6543269),
('1985-12-01',9005566),
('1980-03-25',235765),
('2001-4-12',9005566)
SELECT * FROM [PRESTAMOS]

/*INSERT INTO [PRESTAMOS]([FECHA_INICIO],[USUARIO])VALUES
(GETDATE(),235765),
(GETDATE(),7632423),
(GETDATE(),76325436),
(GETDATE(),6436756),
(GETDATE(),6436756),
(GETDATE(),76325436)
SELECT * FROM [PRESTAMOS]*/

INSERT INTO [DETALLES]([FECHA_FINAL],[PRESTAMO],[COPIA])VALUES
('2002-03-15',1,4),
('1980-03-25',1,3),
('2002-11-15',3,2),
('1850-03-25',5,2),
('1980-03-25',4,5),
('2001-12-12',3,1)
SELECT * FROM [DETALLES]